<?php

declare(strict_types=1);

return [
    'GET health' => 'common/health/index',
    'POST api/v1/auth/signup' => 'auth/auth/signup',
    'POST api/v1/auth/login' => 'auth/auth/login',
    'POST api/v1/auth/logout' => 'auth/auth/logout',
    'POST api/v1/auth/refresh' => 'auth/auth/refresh',
    'POST api/v1/auth/verify-email' => 'auth/auth/verify-email',
    'POST api/v1/auth/request-password-reset' => 'auth/auth/request-password-reset',
    'POST api/v1/auth/reset-password' => 'auth/auth/reset-password',
    'GET api/v1/users/<id:\d+>' => 'user/user/view',
    'GET api/v1/users/<id:\d+>/activity' => 'user/user/activity',
    'GET api/v1/users/<id:\d+>/ratings' => 'user/user/recent-ratings',
    'GET api/v1/users/<id:\d+>/posts' => 'user/user/posts',
    'GET api/v1/movies' => 'movie/movie/index',
    'GET api/v1/movies/<id:\d+>' => 'movie/movie/view',
    'POST api/v1/movies/<id:\d+>/watch' => 'movie/movie/watch',
    'GET api/v1/playlists' => 'playlist/playlist/index',
    'POST api/v1/playlists' => 'playlist/playlist/create',
    'GET api/v1/playlists/<id:\d+>' => 'playlist/playlist/view',
    'PATCH api/v1/playlists/<id:\d+>' => 'playlist/playlist/update',
    'DELETE api/v1/playlists/<id:\d+>' => 'playlist/playlist/delete',
    'POST api/v1/playlists/<id:\d+>/movies' => 'playlist/playlist/add-movie',
    'DELETE api/v1/playlists/<id:\d+>/movies/<movieId:\d+>' => 'playlist/playlist/remove-movie',
    'GET api/v1/reviews' => 'review/review/index',
    'GET api/v1/reviews/<id:\d+>' => 'review/review/view',
    'POST api/v1/reviews' => 'review/review/create',
    'PATCH api/v1/reviews/<id:\d+>' => 'review/review/update',
    'DELETE api/v1/reviews/<id:\d+>' => 'review/review/delete',
    'GET api/v1/ratings' => 'rating/rating/index',
    'GET api/v1/ratings/history' => 'rating/rating/history',
    'GET api/v1/ratings/<id:\d+>' => 'rating/rating/view',
    'POST api/v1/ratings' => 'rating/rating/create',
    'PATCH api/v1/ratings/<id:\d+>' => 'rating/rating/update',
    'DELETE api/v1/ratings/<id:\d+>' => 'rating/rating/delete',
    'GET api/v1/comments' => 'comment/comment/index',
    'GET api/v1/comments/<id:\d+>' => 'comment/comment/view',
    'POST api/v1/comments' => 'comment/comment/create',
    'POST api/v1/comments/<id:\d+>/replies' => 'comment/comment/reply',
    'PATCH api/v1/comments/<id:\d+>' => 'comment/comment/update',
    'DELETE api/v1/comments/<id:\d+>' => 'comment/comment/delete',
    'POST api/v1/comments/<id:\d+>/like' => 'comment/comment/like',
    'GET api/v1/feed' => 'feed/feed/index',
    'GET api/v1/recommendations' => 'recommendation/recommendation/index',
    'POST api/v1/integrations/tmdb/sync' => 'integration/integration/tmdb-sync',
    'GET api/v1/notifications' => 'notification/notification/index',
    'GET api/v1/search' => 'search/search/index',
];
